/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
 * Generated on: 01-Sep-2022 14:48:17
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/*
 * fpass=10Hz , fstop=50Hz , Astop=80dB , fs=1kHz
 */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
#define N_CURRENTLOWPASS 64

extern const float b_currentlowpass[N_CURRENTLOWPASS];
